### ISSUE TITLE
Use devicemanager of infi issue

### ISSUE THREAD

**Issue by newperry** [Infinidat/infi.devicemanager#10]
I want to show device Info. of manager on windows 7 in Python.
My code in below. But it show "RuntimeError: generator raised StopIteration" at dm.all_devices() when I run it.
I use Python 3.7. I don't know what is wrong.

from infi.devicemanager import DeviceManager
dm = DeviceManager()
all_dev = dm.all_devices()

**Comment by wiggin15** [comment]
Hi @newperry.
`dm.all_devices` is a property of type `list`, and not a method. You should use it without the parentheses. 
When I try to run your code, I get:
`TypeError: 'list' object is not callable`

**Comment by wiggin15** [comment]
We also fixed a problem with Python 3.7 in commit d6a28be. Please try to use the latest code from this repository.

**Comment by newperry** [comment]
Thank you for your help.
I can get Info. of device manager after I fixed commit d6a28be and remove parentheses
