### ISSUE TITLE
Device __repr__ method unicode description handling

### ISSUE THREAD

**Issue by timson** [Infinidat/infi.devicemanager#4]
Hi! On my Windows 7 installation, I have device with non ascii description, due this I get UnicodeEncodeError here: infi.devicemanager/src/infi/devicemanager/__init__.py on line 21.

return "<{}>".format(self.friendly_name if self.has_property("friendly_name")else self.description)

replacing "<{}>" with u"<{}>" fix it, but i did not dig deeply into this, is it safe to fix it this way?

**Comment by wiggin15** [comment]
Yes, this looks like the right fix - `disk.friendly_name` is always unicode so the strings formatted with it need to be unicode too. I don't see other string formatting or uses of 'friendly_name' so I believe this fix will be enough.
Do you mind opening a pull request with the fix? Thanks!
