### ISSUE TITLE
Can you release latest version to pypi?

### ISSUE THREAD

**Issue by MakaronKanon** [Infinidat/infi.devicemanager#9]
The last commit in branch develop got a commit  that makes it work with python 3.7 (return instead of raise StopIteration). Could you publish that version so i can download it with pip from pypi website? 

I tried pip install directly from github but there is something special going on with setup.in and buildout.cfg that I dont understand.

**Comment by wiggin15** [comment]
The latest version 0.2.22 was uploaded to PyPI.
